title = input()
content = input()
comment = input()
print("<h1>")
print(f"    {title}")
print("</h1>")
print("<article>")
print(f"    {content}")
print("</article>")
while not comment == "end of comments":
    print("<div>")
    print(f"    {comment}")
    print("</div>")
    comment = input()